name: Mobile

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  repo:
    if: github.repository == 'envoyproxy/envoy'
    name: mobile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy/envoy
    - id: should_run
      name: 'Check what to run'
      run: ./mobile/tools/what_to_run.sh
    - id: should_run
      name: 'Check output'
      run: |
        echo "$GITHUB_OUTPUT"
